### ISSUE TITLE
patch 4.16

### ISSUE THREAD

**Issue by numsu** [tnajdek/lol-eyefinity-surround-fixhud#2]
Patch 4.16 broke the champion info into pieces, half of it is on my first screen and the stats and the relic is on my main screen only

**Comment by tnajdek** [comment]
yepp, I can confirm it did indeed.

It's likely that reinstalling a fresh copy and re-applying hud fixer will resolve this issue. I'll look into this.

**Comment by tnajdek** [comment]
just executed on a fresh copy and works like a charm. Try re-running or running on a fresh/backup copy to get it back to a state where everything fits in perfectly.

Unfortunately every time Riot does a patch to the GUI some of my hudfixes can break :(

**Comment by tnajdek** [comment]
scrap that, turns out it breaks the game when applied to 4.16 or after. Reopening

**Comment by tnajdek** [comment]
Applying to >=4.16  **sometimes** breaks the game :(

**Comment by tnajdek** [comment]
Released a new version which works again
